"""IJarvisAgent — Abstract base class for background agents.

Agents run on a schedule, collecting data and caching results for injection
into voice request context.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, Dict, List

from .secret import IJarvisSecret


@dataclass
class AgentSchedule:
    """Schedule configuration for an agent."""

    interval_seconds: int
    run_on_startup: bool = True


@dataclass
class Alert:
    """A time-sensitive notification produced by a background agent."""

    source_agent: str
    title: str
    summary: str
    priority: int = 2  # 1=low, 2=medium, 3=high


class IJarvisAgent(ABC):
    """Abstract base class for background agents."""

    @property
    @abstractmethod
    def name(self) -> str:
        """Unique identifier for this agent."""
        ...

    @property
    @abstractmethod
    def description(self) -> str:
        """Human-readable description."""
        ...

    @property
    @abstractmethod
    def schedule(self) -> AgentSchedule:
        """When this agent should run."""
        ...

    @property
    @abstractmethod
    def required_secrets(self) -> List[IJarvisSecret]:
        """Secrets this agent needs to function."""
        ...

    @abstractmethod
    async def run(self) -> None:
        """Execute the background task."""
        ...

    @property
    def include_in_context(self) -> bool:
        """Whether to include this agent's data in voice request context."""
        return True

    @abstractmethod
    def get_context_data(self) -> Dict[str, Any]:
        """Return cached data for voice request context."""
        ...

    def get_alerts(self) -> List[Alert]:
        """Return alerts generated by the last run()."""
        return []
